= Atbash MicroProfile rest client
Rudy De Busscher <rdebusscher@gmail.com>
v0.5.1.1, 16/03/2019

== Release notes

include::release.adi[]

== Important remark

Since RestEasy client also contains an integration of MicroProfile RestClient, applications using the Atbash Rest Client do not work when using the @RegisterRestClient. This is because WildFly 12 and WildFly 13 for example contain this RestEasy version but do not supply the MicroProfile Config as module readable from the RestEasy Module.

This will be addressed in a later version.

== Usage

include::javaee.adi[]

include::javase.adi[]

=== Global provider

With the help of the interface *org.eclipse.microprofile.rest.client.spi.RestClientBuilderListener*, we can specify the providers which are applied to all generated rest clients.

Define the implementing class through ServiceLoader configuration, and by implementing the method _onNewBuilder_ have have the change of adding providers to the Rest client in a global way.

You no longer need to add the provider to each individual interface with the use of the @RegisterProvider annotation.
